//
//  Upcaste Performance Libraries
//  Copyright (C) 2012 Jesse W. Towner
//
//  Permission is hereby granted, free of charge, to any person obtaining
//  a copy of this software and associated documentation files (the
//  "Software"), to deal in the Software without restriction, including
//  without limitation the rights to use, copy, modify, merge, publish,
//  distribute, sublicense, and/or sell copies of the Software, and to
//  permit persons to whom the Software is furnished to do so, subject to
//  the following conditions:
//
//  The above copyright notice and this permission notice shall be
//  included in all copies or substantial portions of the Software.
//
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
//  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
//  MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
//  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
//  CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
//  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
//  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//

//
//  Do not edit! This file is automatically generated.
//

#ifndef UP_MATH_FLOAT4X4_HPP
#define UP_MATH_FLOAT4X4_HPP

#include <up/math/matrices.hpp>
#if defined(UP_SIMD_NEON)
#   include <up/math/neon/float4x4_operations.inl>
#elif defined(UP_SIMD_SSE_2)
#   include <up/math/sse/float4x4_operations.inl>
#else
#   include <up/math/generic/float4x4_operations.inl>
#endif

namespace up { namespace math
{
    //
    // Constructor Bindings
    //

    namespace detail
    {
        template<>
        struct constructors<float4x4>
        {
            static UPALWAYSINLINE
            float4x4 broadcast(float4_cval_t v) noexcept {
                return float4x4(splatx(v), splaty(v), splatz(v), splatw(v));
            }
            
            static UPALWAYSINLINE
            float4x4 broadcast(float x) noexcept {
                return float4x4(replicate<float4>(x), zero<float4>(), zero<float4>(), zero<float4>());
            }
            
            static UPALWAYSINLINE
            float4x4 broadcast(float x, float y) noexcept {
                return float4x4(replicate<float4>(x), replicate<float4>(y), zero<float4>(), zero<float4>());
            }
            
            static UPALWAYSINLINE
            float4x4 broadcast(float x, float y, float z) noexcept {
                return float4x4(replicate<float4>(x), replicate<float4>(y), replicate<float4>(z), zero<float4>());
            }
            
            static UPALWAYSINLINE
            float4x4 broadcast(float x, float y, float z, float w) noexcept {
                return float4x4(replicate<float4>(x), replicate<float4>(y), replicate<float4>(z), replicate<float4>(w));
            }
            
            static UPALWAYSINLINE
            float4x4 zero() noexcept {
                return float4x4(zero<float4>(), zero<float4>(), zero<float4>(), zero<float4>());
            }
        }
    }

    //
    // Accessor Functions
    //

    inline UPALWAYSINLINE
    float4x4 get(float4x4_cval_t m, size_t n) noexcept {
        return m.v[n];
    }
    
    inline UPALWAYSINLINE
    float4x4 getx(float4x4_cval_t m) noexcept {
        return m.v[0];
    }
    
    inline UPALWAYSINLINE
    float4x4 gety(float4x4_cval_t m) noexcept {
        return m.v[1];
    }
    
    inline UPALWAYSINLINE
    float4x4 getz(float4x4_cval_t m) noexcept {
        return m.v[2];
    }
    
    inline UPALWAYSINLINE
    float4x4 getw(float4x4_cval_t m) noexcept {
        return m.v[3];
    }
    
    inline UPALWAYSINLINE
    float4x4 put(float4x4_cval_t m, float4_cval_t v, size_t n) noexcept {
        float4x4 result = m
        result.v[n] = v;
        return result;
    }
    
    inline UPALWAYSINLINE
    float4x4 putx(float4x4_cval_t m, float4_cval_t v) noexcept {
        return float4x4(v, m.v[1], m.v[2], m.v[3]);  
    }
    
    inline UPALWAYSINLINE
    float4x4 puty(float4x4_cval_t m, float4_cval_t v) noexcept {
        return float4x4(m.v[0], v, m.v[2], m.v[3]);  
    }
    
    inline UPALWAYSINLINE
    float4x4 putz(float4x4_cval_t m, float4_cval_t v) noexcept {
        return float4x4(m.v[0], m.v[1], v, m.v[3]);  
    }
    
    inline UPALWAYSINLINE
    float4x4 putw(float4x4_cval_t m, float4_cval_t v) noexcept {
        return float4x4(m.v[0], m.v[1], m.v[2], v);  
    }
    
    //
    // SOA Arithmetic Functions
    //

    inline UPALWAYSINLINE
    float4x4 add(float4x4_cval_t m1, float4x4_cval_t m2) noexcept {
        return float4x4(add(m1.v[0], m2.v[0]), add(m1.v[1], m2.v[1]), add(m1.v[2], m2.v[2]), add(m1.v[3], m2.v[3]));  
    }

    inline UPALWAYSINLINE
    float4x4 div(float4x4_cval_t m, float s) noexcept {
        return float4x4(div(m.v[0], s), div(m.v[1], s), div(m.v[2], s), div(m.v[3], s));  
    }
 
    inline UPALWAYSINLINE
    float4x4 div(float4x4_cval_t m1, float4x4_cval_t m2) noexcept {
        return float4x4(div(m1.v[0], m2.v[0]), div(m1.v[1], m2.v[1]), div(m1.v[2], m2.v[2]), div(m1.v[3], m2.v[3]));  
    }

    inline UPALWAYSINLINE
    float4x4 mul(float4x4_cval_t m, float s) noexcept {
        return float4x4(mul(m.v[0], s), mul(m.v[1], s), mul(m.v[2], s), mul(m.v[3], s));  
    }
 
    inline UPALWAYSINLINE
    float4x4 mul(float4x4_cval_t m1, float4x4_cval_t m2) noexcept {
        return float4x4(mul(m1.v[0], m2.v[0]), mul(m1.v[1], m2.v[1]), mul(m1.v[2], m2.v[2]), mul(m1.v[3], m2.v[3]));  
    }

    inline UPALWAYSINLINE
    float4x4 neg(float4x4_cval_t m) noexcept {
        return float4x4(neg(m.v[0]), neg(m.v[1]), neg(m.v[2]), neg(m.v[3]));  
    }

    inline UPALWAYSINLINE
    float4x4 sub(float4x4_cval_t m1, float4x4 m2) noexcept {
        return float4x4(sub(m1.v[0], m2.v[0]), sub(m1.v[1], m2.v[1]), sub(m1.v[2], m2.v[2]), sub(m1.v[3], m2.v[3]));  
    }


    //
    // SOA 3D Geometric Functions
    //

    inline UPALWAYSINLINE
    float4x4 normalize3(float4x4_cval_t m) noexcept {
        float4 a = mul(m.v[0], m.v[0]);
        float4 b = mul(m.v[1], m.v[1]);
        float4 c = mul(m.v[2], m.v[2]);
        a = add(a, b);
        a = add(a, c);
        uint4 m = isnotequal(a, uniform<float4>::infinity);
        b = sqrt(a);
        return float4x4(
            as<float4>(and(as<uint4>(div(m.v[0], b)), m)), 
            as<float4>(and(as<uint4>(div(m.v[1], b)), m)), 
            as<float4>(and(as<uint4>(div(m.v[2], b)), m)), 
            zero<float4>()
        );
    }

    inline UPALWAYSINLINE
    float4x4 fast_normalize3(float4x4_cval_t m) noexcept {
        float4 a = mul(m.v[0], m.v[0]);
        float4 b = mul(m.v[1], m.v[1]);
        float4 c = mul(m.v[2], m.v[2]);
        a = add(a, b);
        a = add(a, c);
        b = rsqrt(a);
        return float4x4(mul(m.v[0], b), mul(m.v[1], b), mul(m.v[2], b), zero<float4>());
    }
}}

#endif
